# Generated by Django 5.0 on 2025-06-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField()),
                ('quilometragem', models.PositiveIntegerField()),
                ('numero_portas', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('combustivel', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='carros/')),
            ],
        ),
    ]
