# Generated by Django 4.2.3 on 2025-05-08 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('comercial', 'Comercial'), ('rural', 'Rural')], max_length=20, verbose_name='Tipo')),
                ('finalidade', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel')], max_length=20, verbose_name='Finalidade')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
                ('metragem', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Metragem')),
                ('quartos', models.PositiveIntegerField(verbose_name='Quartos')),
                ('banheiros', models.PositiveIntegerField(verbose_name='Banheiros')),
                ('vagas', models.PositiveIntegerField(verbose_name='Vagas de Garagem')),
                ('ano_fabricacao', models.PositiveIntegerField(verbose_name='Ano de Fabricação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/%Y/%m/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['ordem'],
            },
        ),
    ]
